# Generated by Django 5.0.4 on 2024-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pooja',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FULL_NAME', models.CharField(max_length=30)),
                ('EMAIL_ADDRESS', models.CharField(max_length=30)),
                ('MOBILE_NUMBER', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=20)),
                ('ADDRESS', models.CharField(max_length=40)),
            ],
        ),
    ]
